# Official daloRADIUS Dockerfile for freeradius
# GitHub: https://github.com/lirantal/daloradius
#
# Build image:
# 1. git pull git@github.com:lirantal/daloradius.git
# 2. docker build -t lirantal/daloradius -f Dockerfile-freeradius
#
# Run the container:
# 1. docker run -p 1812:1812/udp -p 1813:1813/udp -d lirantal/dalofreeradius

FROM freeradius/freeradius-server:3.2.8
LABEL maintainer="Liran Tal <liran.tal@gmail.com>"
LABEL Description="FreeRADIUS 3.2.8 Docker image optimized for daloRADIUS." \
	License="GPLv2" \
	Usage="docker build -t lirantal/dalofreeradius -f Dockerfile-freeradius && docker run -d -p 1812:1812/udp -p 1813:1813/udp lirantal/dalofreeradius" \
	Version="1.0"

ENV DEBIAN_FRONTEND=noninteractive

# default timezone
ENV TZ=Europe/Vienna

RUN apt-get update \
	&& apt-get install --yes --no-install-recommends \
		ipcalc \
		tzdata \
		net-tools \
		mariadb-client \
	&& rm -rf /var/lib/apt/lists/*

# Create directories
# /data should be mounted as volume to avoid recreation of database entries
RUN mkdir /app /data
WORKDIR /app

# Copy init script to image
COPY ./init-freeradius.sh /app

# Make init.sh script executable
RUN sed -i 's/\r$//' /app/init-freeradius.sh \
	&& chmod +x /app/init-freeradius.sh

# Expose FreeRADIUS Ports
EXPOSE 1812 1813

ENTRYPOINT ["/app/init-freeradius.sh"]
