services:

  radius-mysql:
    image: mariadb:10
    container_name: radius-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - "./data/mysql:/var/lib/mysql"
      # Optional: mount host timezone files (helpful on Linux hosts)
      # - "/etc/localtime:/etc/localtime:ro"
      # - "/etc/timezone:/etc/timezone:ro"

  radius:
    container_name: radius
    build:
      context: .
      dockerfile: docker/freeradius/dockerfile-freeradius
    restart: unless-stopped
    depends_on: 
      - radius-mysql
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
      # Optional settings
      - DEFAULT_CLIENT_SECRET=${DEFAULT_CLIENT_SECRET}
    volumes:
      - ./data/freeradius:/data
      - ./radius_logs:/var/log/freeradius
    # Uncomment below to enable debug logging.
    #command: -X

  radius-web:
    build:
      context: .
      dockerfile: docker/daloradius/dockerfile
    container_name: daloradius
    restart: unless-stopped
    depends_on:
      - radius
      - radius-mysql
    ports:
      - '80:80'
      - '8000:8000'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
      # Optional Settings:
      - DEFAULT_CLIENT_SECRET=${DEFAULT_CLIENT_SECRET}
      - DEFAULT_FREERADIUS_SERVER=${DEFAULT_FREERADIUS_SERVER}
      - MAIL_SMTPADDR=${MAIL_SMTPADDR}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_AUTH=${MAIL_AUTH}

    volumes:
      - ./data/daloradius:/data
      - ./radius_logs:/var/log/freeradius

volumes:
  radius_logs:
