#!/usr/bin/env python3
"""UNIT-044: isolated real PHP/PEAR/PDO + MariaDB; never export passwords/hashes.

Fixture inputs are generated by PHP in memory and kept only in tmpfs MariaDB.
Probes return booleans/counters, not credential snapshots. No live DB/config.
"""
import concurrent.futures
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import tempfile
import urllib.error
import urllib.request

from expired_accounts_retirement import run, wait_for

ROOT = Path(__file__).resolve().parents[1]
BASE = '892a018703fdfbcb3fecadb4e7a4721c391ec136'
BASELINE = os.environ.get('PORTAL_HASH_BASELINE') == '1'
TAG = 'u44-' + secrets.token_hex(6)
DB, WEB, NET = (TAG + '-' + suffix for suffix in ('db', 'web', 'net'))
PATH = 'contrib/scripts/maintenance/hash-user-portal-passwords.php'
TABLE = 'u44_userinfo'

PROBE = r'''<?php
try {
    require __DIR__ . '/app/common/includes/config_read.php';
    require __DIR__ . '/app/common/includes/portal_password.php';
    require __DIR__ . '/app/common/includes/pdo_connection.php';
    $pdo=dalo_pdo_connect($configValues);
    $action=$argv[1];
    if (strpos($action,'seed')===0) {
        $pdo->exec('TRUNCATE TABLE u44_userinfo; TRUNCATE TABLE fixture_expected');
        $insert=$pdo->prepare('INSERT INTO u44_userinfo(id,username,portalloginpassword,notes) VALUES(?,?,?,?)');
        $expect=$pdo->prepare('INSERT INTO fixture_expected(id,value,kind) VALUES(?,?,?)');
        $rows=array();
        if ($action==='seed-normal' || $action==='seed-nul') {
            $rows=array(
                array(1,null,'preserve'),array(3,'','preserve'),
                array(5,'legacy-'.bin2hex(random_bytes(16)),'migrate'),
                array(7,dalo_portal_password_hash(bin2hex(random_bytes(16))),'preserve'),
                array(9,'0','migrate'),
                array(11,"quote'-%-+-é-".bin2hex(random_bytes(12)).' ','migrate'),
                array(13,password_hash(bin2hex(random_bytes(16)),PASSWORD_DEFAULT),'migrate'),
                array(15,dalo_portal_password_prefix().bin2hex(random_bytes(16)),'migrate')
            );
            if ($action==='seed-nul') $rows[]=array(17,bin2hex(random_bytes(16))."\0".bin2hex(random_bytes(8)),'preserve');
        } elseif ($action==='seed-pair') {
            $rows=array(array(5,'legacy-'.bin2hex(random_bytes(16)),'migrate'),array(9,'next-'.bin2hex(random_bytes(16)),'migrate'));
        }
        foreach($rows as $row) {
            $insert->execute(array($row[0],'fixture-'.$row[0],$row[1],'fixture-notes'));
            $expect->execute($row);
        }
        echo json_encode(array('seeded'=>true));
    } elseif ($action==='verify-exact' || $action==='verify-migrated' || $action==='verify-error') {
        $okay=true;$count=0;
        $rows=$pdo->query('SELECT e.id,e.value,e.kind,u.id AS actual_id,u.portalloginpassword,u.notes,u.username
                          FROM fixture_expected e LEFT JOIN u44_userinfo u ON u.id=e.id ORDER BY e.id')->fetchAll();
        foreach($rows as $row) {
            $count++;
            if ($row['kind']==='deleted') {$okay=$okay && $row['actual_id']===null;continue;}
            if($row['actual_id']===null) {$okay=false;continue;}
            $stored=$row['portalloginpassword'];$value=$row['value'];
            $migrate=$action!=='verify-exact' && $row['kind']==='migrate';
            if($action==='verify-error' && (int)$row['id']===9)$migrate=false;
            if($migrate) {
                $okay=$okay && dalo_portal_password_is_hash($stored)
                    && password_verify($value,substr($stored,strlen(dalo_portal_password_prefix())));
            } else {$okay=$okay && $stored===$value;}
            $okay=$okay && $row['notes']==='fixture-notes' && $row['username']==='fixture-'.$row['id'];
        }
        $actual=(int)$pdo->query('SELECT COUNT(*) FROM u44_userinfo')->fetchColumn();
        $deleted=(int)$pdo->query("SELECT COUNT(*) FROM fixture_expected WHERE kind='deleted'")->fetchColumn();
        echo json_encode(array('valid'=>$okay && $actual===$count-$deleted));
    } elseif ($action==='verify-truncated') {
        $okay=true;$count=0;
        foreach($pdo->query('SELECT e.value,u.portalloginpassword FROM fixture_expected e JOIN u44_userinfo u ON u.id=e.id') as $row) {
            $count++;
            $stored=$row['portalloginpassword'];
            $okay=$okay && $stored!==$row['value'] && !dalo_portal_password_is_hash($stored)
                && !password_verify($row['value'],substr($stored,strlen(dalo_portal_password_prefix())));
        }
        echo json_encode(array('valid'=>$okay && $count===2));
    } elseif (strpos($action,'reset-')===0) {
        $old=$pdo->query('SELECT value FROM fixture_expected WHERE id=5')->fetchColumn();
        $mode=substr($action,6);
        if($mode==='delete') {
            $pdo->exec("DELETE FROM u44_userinfo WHERE id=5; UPDATE fixture_expected SET kind='deleted' WHERE id=5");
        } else {
            $replacement=$mode==='case' ? strtoupper($old) : ($mode==='trailing' ? $old.' ' : dalo_portal_password_hash(bin2hex(random_bytes(16))));
            $pdo->prepare('UPDATE u44_userinfo SET portalloginpassword=? WHERE id=5')->execute(array($replacement));
            $pdo->prepare("UPDATE fixture_expected SET value=?,kind='preserve' WHERE id=5")->execute(array($replacement));
        }
        echo json_encode(array('reset'=>true));
    } else {throw new RuntimeException('Unknown fixture action');}
} catch(Throwable $error) {fwrite(STDERR,"Fixture probe failed.\n");exit(1);}
'''

# Fixture-only synchronization after batch read and before native password_hash.
# Real crypto and the production script are not mocked/replaced.
PAUSE = r'''
    static $fixture_paused=false;
    if (!$fixture_paused && getenv('FIXTURE_CAS_PAUSE')==='1'
        && basename($_SERVER['SCRIPT_FILENAME'] ?? '')==='hash-user-portal-passwords.php') {
        $fixture_paused=true;
        file_put_contents('/run/u44-ready','ready');
        $limit=microtime(true)+30;
        while(!is_file('/run/u44-resume')) {
            if(microtime(true)>$limit)throw new RuntimeException('Fixture synchronization timeout');
            usleep(20000);
        }
    }
'''


def sql(query):
    p = run('docker', 'exec', '-i', DB, 'mariadb', '-uroot', '-N', '-B', 'fixture', input="SET SESSION sql_mode='';\n" + query, check=False)
    if p.returncode:
        raise RuntimeError('Fixture SQL failed; details omitted')
    return p.stdout.strip()


def probe(action):
    p = run('docker', 'exec', '-e', 'FIXTURE_DB_USER=root', '-e', 'FIXTURE_DB_PASS=', WEB,
            'php', '-d', 'display_errors=0', '/fixtures/probe.php', action, check=False)
    assert p.returncode == 0 and p.stderr == ''
    result = json.loads(p.stdout)
    assert len(result) == 1 and next(iter(result.values())) is True


def cli(*args, pause=False, cwd='/'):
    command = ['docker', 'exec', '-w', cwd]
    if pause:
        command += ['-e', 'FIXTURE_CAS_PAUSE=1']
    return run(*command, WEB, 'php', '-d', 'display_errors=0', '-d', 'error_reporting=8191',
               '/fixtures/' + PATH, *args, check=False, timeout=90)


def counts(p, scanned, empty=0, hashed=0, migrated=0, conflicts=0, failed=0, dry=False):
    assert p.returncode == (1 if failed else 0) and p.stderr == ''
    expected = ('DRY RUN' if dry else 'COMPLETE') + ': scanned=%d empty=%d already_hashed=%d %s=%d conflicted=%d failed=%d\n' % (
        scanned, empty, hashed, 'would_migrate' if dry else 'migrated', migrated, conflicts, failed)
    assert p.stdout == expected


def configure(common, table=TABLE):
    text = '<?php\n$configValues=array();\n'
    for field in ('ENGINE', 'HOST', 'PORT', 'NAME', 'USER', 'PASS'):
        text += "$configValues['CONFIG_DB_" + field + "']=getenv('FIXTURE_DB_" + field + "');\n"
    text += "$configValues['FREERADIUS_VERSION']='3';\n"
    text += "$configValues['CONFIG_DB_TBL_DALOUSERINFO']='" + table.replace("'", "\\'") + "';\n"
    (common / 'daloradius.conf.php').write_text(text)


def main():
    scratch = Path.home() / '.hermes/cache/scratch'
    scratch.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='portal-hash-', dir=scratch) as directory:
        fixture = Path(directory)
        script = fixture / PATH
        script.parent.mkdir(parents=True)
        script.write_text(run('git', 'show', BASE + ':' + PATH).stdout) if BASELINE else shutil.copy2(ROOT / PATH, script)
        common = fixture / 'app/common/includes'
        common.mkdir(parents=True)
        for name in ('config_read.php', 'version.php', 'pdo_connection.php', 'portal_password.php',
                     'db_open.php', 'db_close.php', 'db_table_conventions.php', 'db_error_handler.php'):
            shutil.copy2(ROOT / 'app/common/includes' / name, common / name)
        original_helper = (common / 'portal_password.php').read_text()
        hook = 'function dalo_portal_password_hash($password) {'
        assert original_helper.count(hook) == 1
        (common / 'portal_password.php').write_text(original_helper.replace(hook, hook + PAUSE))
        configure(common)
        (fixture / 'health.php').write_text('<?php echo "ready";')
        (fixture / 'probe.php').write_text(PROBE)
        user, password = 'fixture_' + secrets.token_hex(5), secrets.token_hex(32)
        try:
            run('docker', 'network', 'create', '--internal', NET)
            run('docker', 'run', '-d', '--name', DB, '--network', NET, '--tmpfs', '/var/lib/mysql',
                '-e', 'MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1', '-e', 'MARIADB_DATABASE=fixture', 'mariadb:11.8')
            wait_for(lambda: sql('SELECT 1') == '1', 'MariaDB')
            schema = (ROOT / 'contrib/db/mariadb-daloradius.sql').read_text()
            begin = schema.index('CREATE TABLE `userinfo` (')
            schema = schema[begin:schema.index(';', begin) + 1].replace('`userinfo`', '`' + TABLE + '`', 1)
            sql(schema + '''CREATE TABLE fixture_expected(id INT PRIMARY KEY,value TEXT NULL,kind VARCHAR(32)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;''')
            sql(f"CREATE USER '{user}'@'%' IDENTIFIED BY '{password}'; GRANT SELECT,UPDATE ON fixture.* TO '{user}'@'%';")
            environment = {'FIXTURE_DB_ENGINE': 'mysqli', 'FIXTURE_DB_HOST': DB, 'FIXTURE_DB_PORT': '3306',
                           'FIXTURE_DB_NAME': 'fixture', 'FIXTURE_DB_USER': user, 'FIXTURE_DB_PASS': password}
            args = ['docker', 'run', '-d', '--name', WEB, '--network', NET, '-v', f'{fixture}:/fixtures:ro']
            for key in environment:
                args += ['-e', key]
            args += ['--entrypoint', 'php', 'lirantal/daloradius', '-d', 'display_errors=0',
                     '-d', 'opcache.enable=0', '-d', 'opcache.enable_cli=0', '-S', '0.0.0.0:8080', '-t', '/fixtures']
            p = subprocess.run(args, env=dict(os.environ, **environment), capture_output=True, text=True, timeout=60)
            assert p.returncode == 0
            environment.clear()
            ip = run('docker', 'inspect', '-f', '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}', WEB).stdout.strip()
            base = 'http://' + ip + ':8080/'
            wait_for(lambda: urllib.request.urlopen(base + 'health.php', timeout=5).read() == b'ready', 'PHP HTTP')
            probe('seed-normal')
            counts(cli('--dry-run', '--batch-size=2'), 8, empty=2, hashed=1, migrated=5, dry=True)
            probe('verify-exact')
            counts(cli('--batch-size=2'), 8, empty=2, hashed=1, migrated=5)
            probe('verify-migrated')
            counts(cli('--batch-size=1'), 8, empty=2, hashed=6)
            probe('verify-migrated')
            probe('seed-empty')
            counts(cli('--batch-size=1000', cwd='/fixtures/contrib/scripts/maintenance'), 0)
            probe('seed-nul')
            counts(cli('--dry-run'), 9, empty=2, hashed=1, migrated=6, dry=True)
            probe('verify-exact')
            counts(cli('--batch-size=2'), 9, empty=2, hashed=1, migrated=5, failed=1)
            probe('verify-migrated')
            print('PASS A/B:', 'unmodified PEAR baseline' if BASELINE else 'PDO candidate',
                  'batch scan, custom real userinfo schema, dry-run invariance, empty/NULL/zero/Unicode/quoted values, marked/unmarked/malformed hashes, NUL failures and idempotence; only counters/booleans returned')
            for mode in ('case', 'trailing', 'hash', 'delete', 'migrator'):
                probe('seed-pair')
                run('docker', 'exec', WEB, 'rm', '-f', '/run/u44-ready', '/run/u44-resume')
                with concurrent.futures.ThreadPoolExecutor(2) as pool:
                    paused = pool.submit(cli, '--batch-size=2', pause=True)
                    wait_for(lambda: run('docker', 'exec', WEB, 'test', '-f', '/run/u44-ready', check=False).returncode == 0, 'post-read synchronization')
                    if mode == 'migrator':
                        counts(cli('--batch-size=2'), 2, migrated=2)
                    else:
                        probe('reset-' + mode)
                    run('docker', 'exec', WEB, 'touch', '/run/u44-resume')
                    p = paused.result()
                counts(p, 2, migrated=0 if mode == 'migrator' else 1, conflicts=2 if mode == 'migrator' else 1)
                probe('verify-migrated')
            print('PASS A/B: native bytewise CAS protects concurrent case/trailing-space reset, replacement hash/deletion and competing migrator; exact conflict counters')
            probe('seed-pair')
            sql(f'''DELIMITER //
              CREATE TRIGGER fixture_row_error BEFORE UPDATE ON {TABLE} FOR EACH ROW BEGIN
                IF OLD.id=9 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture-row-error'; END IF;
              END//
              DELIMITER ;''')
            counts(cli('--batch-size=1'), 2, migrated=1, failed=1)
            probe('verify-error')
            sql('DROP TRIGGER fixture_row_error')
            print('PASS A/B: later row SQL error leaves earlier successful CAS migrated, preserves failed row and exits 1')
            probe('seed-normal')
            sql(f"REVOKE UPDATE ON fixture.* FROM '{user}'@'%'")
            counts(cli('--dry-run'), 8, empty=2, hashed=1, migrated=5, dry=True)
            probe('verify-exact')
            counts(cli('--batch-size=2'), 8, empty=2, hashed=1, failed=5)
            probe('verify-exact')
            sql(f"GRANT UPDATE ON fixture.* TO '{user}'@'%'")
            sql(f"REVOKE SELECT ON fixture.* FROM '{user}'@'%'")
            counts(cli(), 0, failed=1)
            sql(f"GRANT SELECT ON fixture.* TO '{user}'@'%'")
            probe('verify-exact')
            print('PASS A/B: SELECT-only dry-run performs no writes; denied UPDATE/SELECT yields exact failure counters without credential output')
            if BASELINE:
                probe('seed-pair')
                sql('ALTER TABLE ' + TABLE + ' MODIFY portalloginpassword VARCHAR(64)')
                counts(cli(), 2, migrated=2)
                probe('verify-truncated')
                sql('ALTER TABLE ' + TABLE + ' MODIFY portalloginpassword VARCHAR(255)')
                print('PASS baseline characterization: narrow schema silently truncates hashes despite success counters; not candidate parity')
            for value in ('0', '1001', 'bad'):
                p = cli('--batch-size=' + value)
                assert p.returncode == 2 and p.stdout == '' and p.stderr == 'batch-size must be between 1 and 1000\n'
            p = cli('--help')
            assert p.returncode == 0 and p.stderr == '' and p.stdout.startswith('Usage: php hash-user-portal-passwords.php')
            if not BASELINE:
                probe('seed-normal')
                for table in ('bad;DROP_TABLE', 'x' * 65, ''):
                    configure(common, table)
                    counts(cli(), 0, failed=1)
                    probe('verify-exact')
                configure(common)
                # Seed short inputs before intentionally narrowing fixture schema.
                probe('seed-pair')
                sql('ALTER TABLE ' + TABLE + ' MODIFY portalloginpassword VARCHAR(64)')
                counts(cli(), 0, failed=1)
                probe('verify-exact')
                sql('ALTER TABLE ' + TABLE + ' MODIFY portalloginpassword VARCHAR(255)')
                sql('ALTER TABLE ' + TABLE + ' MODIFY id INT UNSIGNED NOT NULL, DROP PRIMARY KEY')
                counts(cli(), 0, failed=1)
                probe('verify-exact')
                sql('ALTER TABLE ' + TABLE + ' ADD PRIMARY KEY(id), MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT')
                sql('RENAME TABLE ' + TABLE + ' TO fixture_backup; CREATE VIEW ' + TABLE + ' AS SELECT * FROM fixture_backup')
                counts(cli(), 0, failed=1)
                probe('verify-exact')
                sql('DROP VIEW ' + TABLE + '; RENAME TABLE fixture_backup TO ' + TABLE)
                print('PASS candidate: invalid identifiers, insufficient hash capacity, missing primary ID and view refused before conversion')
            probe('seed-pair')
            (common / 'config_read.php').write_text("<?php throw new RuntimeException('config-tripwire');")
            for method in ('GET', 'POST', 'HEAD', 'PUT'):
                req = urllib.request.Request(base + PATH, method=method, data=b'force=1' if method in ('POST', 'PUT') else None)
                try:
                    response = urllib.request.urlopen(req, timeout=10)
                except urllib.error.HTTPError as error:
                    response = error
                assert response.status == 404 and response.read() == b''
            p = cli('--help')
            assert p.returncode == 0 and p.stderr == ''
            p = cli('--batch-size=0')
            assert p.returncode == 2
            shutil.copy2(ROOT / 'app/common/includes/config_read.php', common / 'config_read.php')
            probe('verify-exact')
            run('docker', 'stop', DB)
            p = cli()
            assert p.returncode == 1 and p.stdout == '' and p.stderr == 'Unable to connect to the database.\n'
            logs = run('docker', 'logs', WEB)
            combined = p.stdout + p.stderr + logs.stdout + logs.stderr
            assert password not in combined and user not in combined and 'config-tripwire' not in combined
            print('PASS A/B: HTTP denied and help/invalid batch validated before config; connection failure redacted')
        finally:
            for name in (WEB, DB):
                run('docker', 'rm', '-f', name, check=False)
            run('docker', 'network', 'rm', NET, check=False)
            for name in (WEB, DB):
                assert run('docker', 'inspect', name, check=False).returncode != 0
            assert run('docker', 'network', 'inspect', NET, check=False).returncode != 0
    assert not fixture.exists()
    print('PASS cleanup: tmpfs fixture credentials, files, DB, containers and network removed; no live account or portal login exercised')


if __name__ == '__main__':
    main()
